name = "strips"
version = "0.1.0"
keywords = ["automated planning", "planning", "strips"]
defaultTargets = ["Strips"]
lintDriver = "batteries/runLinter"

[[require]]
name = "Parser"
# git = "https://github.com/fgdorais/lean4-parser"
git = "https://github.com/AmosNico/lean4-parser"
rev = "40ccb6dcacdcdb9bf1c403225ed80827003e626a"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.31.0"

[[lean_lib]]
name = "Strips"

[[lean_exe]]
name = "test-parser"
root = "Test"