name = "strips"
version = "0.1.0"
keywords = ["automated planning", "planning", "strips"]
defaultTargets = ["Strips"]
lintDriver = "batteries/runLinter"

[[require]]
name = "Parser"
# the version v4.29.1 was skiped, use fork
# git = "https://github.com/fgdorais/lean4-parser"
git = "https://gitlab.kuleuven.be/u0185131/lean4-parser.git"
rev = "v4.29.1"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.30.0"

[[lean_lib]]
name = "Strips"

[[lean_exe]]
name = "test-parser"
root = "Test"